export const projects = [
    {
        title: 'Gaurastra',
        description: 'A full-stack e-commerce platform built using MERN Stack together with SASS.',
        technologies: ['React.js', 'JavaScript','Node.js', 'SASS', 'Phonepe'],
        githubLink: 'https://github.com',
        demoLink: 'https://www.gaurastra.com/',
        image: '/projects/Gaurastra.png',
      },
      {
        title: 'Caribbeaneaze',
        description: "A full-stack hotel booking platform built using MERN Stack together with Socket.io.",
        technologies: ['React', 'Node.js','JavaScript','MongoDB', 'Socket.io'],
        githubLink: 'https://github.com',
        demoLink: 'https://www.caribbeaneaze.com/',
        image: '/projects/caribbeaneaze.png',
      },
      {
        title: 'StrategyPCS',
        description: 'A full-stack e-learning platform built using MERN Stack together with Tailwind CSS.',
        technologies: ['React.js', 'JavaScript','Node.js', 'Tailwind CSS'],
        githubLink: 'https://github.com',
        demoLink: 'https://www.strategypcs.in/',
        image: '/projects/StrategyPCS.png',
      },
      // {
      //   title: 'Weather App',
      //   description: 'A weather application that provides real-time weather updates.',
      //   technologies: ['React', 'OpenWeatherMap API'],
      //   githubLink: 'https://github.com',
      //   demoLink: 'https://demo.com',
      //   image: '/projects/weather-app.png',
      // },
      // {
      //   title: 'Chat Application',
      //   description: 'A real-time chat application using WebSocket technology.',
      //   technologies: ['React', 'Node.js', 'Socket.io'],
      //   githubLink: 'https://github.com',
      //   demoLink: 'https://demo.com',
      //   image: '/projects/chat-app.png',
      // },
      // {
      //   title: 'Recipe Finder',
      //   description: 'A recipe search application using the Edamam API.',
      //   technologies: ['React', 'Edamam API'],
      //   githubLink: 'https://github.com',
      //   demoLink: 'https://demo.com',
      //   image: '/projects/recipe-finder.png',
      // },
      // {
      //   title: 'Expense Tracker',
      //   description: 'A personal finance tracker to manage expenses and income.',
      //   technologies: ['React', 'Firebase'],
      //   githubLink: 'https://github.com',
      //   demoLink: 'https://demo.com',
      //   image: '/projects/expense-tracker.webp',
      // }
  ];